### ISSUE TITLE
Loading dependencies

### ISSUE THREAD

**Issue by lukeyouell** [xkisu/craftcookieconsent#3]
It would be great if we could toggle automatic dependency loading on/off.

We use RequireJS with most of our projects and would prefer to load the js this way instead.

**Comment by xkisu** [comment]
I'm not sure this is such a good idea due to compatibility. By having the plugin loading it's version of cookieconsent I can ensure it's the correct version and that it's compatible with the plugin. 

Otherwise I can't ensure that the way the plugin initializes cookie consent will work with other version of cookie consent so it could easily break, or that cookie consent and the plugin initialization script is loaded in the right order. 

I'm open to suggestions, but for now I don't plan to add a toggle for it. 😉
